### PR TITLE
Run everything in Docker

### PR DESCRIPTION
**Pull request by kjenneycloudhealth**
Thanks for this bit of code. It helped me out a lot so I'd though I'd share what I did with it.

### CODE REVIEW

**Comment by ciaransweet** [comment]
@kjenneycloudhealth hey thanks for the PR 😄 How did you come across the Repo?

Going to keep this PR open, it's perfectly fine and many thanks for the contribution but the way the blog I wrote flows doesn't quite fit into the fully docker route.

I'll make an amendment to the blog which points to this for an example of a fully dockerised option, if that's okay?

**Comment by kjenneycloudhealth** [comment]
@ciaranevans That's fine. Thanks again for saving me a bunch of time.

**Comment by ciaransweet** [comment]
> @ciaranevans That's fine. Thanks again for saving me a bunch of time.

@kjenneycloudhealth  No problem! Was it just a lucky google find?

**Comment by kjenneycloudhealth** [comment]
Sorry, missed the original question. Yes - it was a quick google to the medium article.

**Comment by ciaransweet** [comment]
> Sorry, missed the original question. Yes - it was a quick google to the medium article.

Haha, that's pretty cool! If you're interested in Lambda Layers + the free version of LocalStack, I've a blog queued up about that too

**Comment by kjenneycloudhealth** [comment]
> > Sorry, missed the original question. Yes - it was a quick google to the medium article.
> 
> Haha, that's pretty cool! If you're interested in Lambda Layers + the free version of LocalStack, I've a blog queued up about that too

I haven't used Lambda Layers yet. It just so happens that most of my projects use Python and pull in additional dependencies. That would be awesome!

**Comment by ciaranevans** [comment]
> > > Sorry, missed the original question. Yes - it was a quick google to the medium article.
> > 
> > 
> > Haha, that's pretty cool! If you're interested in Lambda Layers + the free version of LocalStack, I've a blog queued up about that too
> 
> I haven't used Lambda Layers yet. It just so happens that most of my projects use Python and pull in additional dependencies. That would be awesome!

**Comment by ciaransweet** [comment]
> > > Sorry, missed the original question. Yes - it was a quick google to the medium article.
> > 
> > 
> > Haha, that's pretty cool! If you're interested in Lambda Layers + the free version of LocalStack, I've a blog queued up about that too
> 
> I haven't used Lambda Layers yet. It just so happens that most of my projects use Python and pull in additional dependencies. That would be awesome!

Cool! I'll give you a shout when it's published (Hopefully wont be long, it's via my works Publication)

**Comment by ciaransweet** [comment]
@kjenneycloudhealth It's out here: https://medium.com/uk-hydrographic-office/lambda-layers-in-localstack-the-free-version-a48c1228176?source=friends_link&sk=d2e9f3f581ef62db65b067942ccc3576 😄

**Comment by ciaransweet** [comment]
@kjenneycloudhealth I'm going to close this PR, thanks again for taking the time to do it, I've linked it in the Blog, sorry it took so long

**Pull request closed without merging**
